---
- hosts: "pfsense"
  become: true
  vars:
    created_username: ansible

  tasks:
    - name: Install 
      apt:
        name: pfsense
        state: latest
        update_cache: true


    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
          - ufw
        state: latest
        update_cache: true
